export const ADD_PRODUCT_TO_ORDER = "ADD_PRODUCT_TO_ORDER";
export const REMOVE_PRODUCT_FROM_ORDER = "REMOVE_PRODUCT_FROM_ORDER";
export const BUY_ORDER = "BUY_ORDER";
export const SEND_ORDER = "SEND_ORDER";
