// Pending orders

export const GET_PENDING_ORDERS = "GET_PENDING_ORDERS"
export const GET_PENDING_ORDERS_PENDING = "GET_PENDING_ORDERS_PENDING"
export const GET_PENDING_ORDERS_FULFILLED = "GET_PENDING_ORDERS_FULLFILLED"
export const GET_PENDING_ORDERS_REJECTED = "GET_PENDING_ORDERS_REJECTED"

export const GET_USER_PENDING_ORDER = "GET_USER_PENDING_ORDER"
export const GET_USER_PENDING_ORDER_PENDING = "GET_USER_PENDING_ORDER_PENDING"
export const GET_USER_PENDING_ORDER_FULFILLED = "GET_USER_PENDING_ORDER_FULLFILLED"
export const GET_USER_PENDING_ORDER_REJECTED = "GET_PENDING_ORDERS_REJECTED"

export const POST_PENDING_ORDER = "POST_PENDING_ORDER"
export const POST_PENDING_ORDER_PENDING = "POST_PENDING_ORDER_PENDING"
export const POST_PENDING_ORDER_FULFILLED = "POST_PENDING_ORDER_FULLFILLED"
export const POST_PENDING_ORDER_REJECTED = "POST_PENDING_ORDER_REJECTED"

export const UPDATE_PENDING_ORDER = "UPDATE_PENDING_ORDER"
export const UPDATE_PENDING_ORDER_PENDING = "UPDATE_PENDING_ORDER_PENDING"
export const UPDATE_PENDING_ORDER_FULFILLED = "UPDATE_PENDING_ORDER_FULLFILLED"
export const UPDATE_PENDING_ORDER_REJECTED = "UPDATE_PENDING_ORDER_REJECTED"

export const REMOVE_PENDING_ORDER = "REMOVE_PENDING_ORDER"
export const REMOVE_PENDING_ORDER_PENDING = "REMOVE_PENDING_ORDER_PENDING"
export const REMOVE_PENDING_ORDER_FULFILLED = "REMOVE_PENDING_ORDER_FULLFILLED"
export const REMOVE_PENDING_ORDER_REJECTED = "REMOVE_PENDING_ORDER_REJECTED"

// Payed orders

export const GET_PAYED_ORDER = "GET_PAYED_ORDER"
export const GET_PAYED_ORDER_PAYED = "GET_PAYED_ORDER_PENDING"
export const GET_PAYED_ORDER_FULFILLED = "GET_PAYED_ORDER_FULLFILLED"
export const GET_PAYED_ORDER_REJECTED = "GET_PAYED_ORDER_REJECTED"

export const POST_PAYED_ORDER = "POST_PAYED_ORDER"
export const POST_PAYED_ORDER_PAYED = "POST_PAYED_ORDER_PENDING"
export const POST_PAYED_ORDER_FULFILLED = "POST_PAYED_ORDER_FULLFILLED"
export const POST_PAYED_ORDER_REJECTED = "POST_PAYED_ORDER_REJECTED"

export const UPDATE_PAYED_ORDER = "UPDATE_PAYED_ORDER"
export const UPDATE_PAYED_ORDER_PAYED = "UPDATE_PAYED_ORDER_PENDING"
export const UPDATE_PAYED_ORDER_FULFILLED = "UPDATE_PAYED_ORDER_FULLFILLED"
export const UPDATE_PAYED_ORDER_REJECTED = "UPDATE_PAYED_ORDER_REJECTED"

export const REMOVE_PAYED_ORDER = "REMOVE_PAYED_ORDER"
export const REMOVE_PAYED_ORDER_PAYED = "REMOVE_PAYED_ORDER_PENDING"
export const REMOVE_PAYED_ORDER_FULFILLED = "REMOVE_PAYED_ORDER_FULLFILLED"
export const REMOVE_PAYED_ORDER_REJECTED = "REMOVE_PAYED_ORDER_REJECTED"