export const GET_PAYED_ORDER = "GET_PAYED_ORDER";
export const GET_PAYED_ORDER_PAYED = "GET_PAYED_ORDER_PENDING";
export const GET_PAYED_ORDER_FULFILLED = "GET_PAYED_ORDER_FULLFILLED";
export const GET_PAYED_ORDER_REJECTED = "GET_PAYED_ORDER_REJECTED";

export const POST_PAYED_ORDER = "POST_PAYED_ORDER";
export const POST_PAYED_ORDER_PAYED = "POST_PAYED_ORDER_PENDING";
export const POST_PAYED_ORDER_FULFILLED = "POST_PAYED_ORDER_FULLFILLED";
export const POST_PAYED_ORDER_REJECTED = "POST_PAYED_ORDER_REJECTED";

export const UPDATE_PAYED_ORDER = "UPDATE_PAYED_ORDER";
export const UPDATE_PAYED_ORDER_PAYED = "UPDATE_PAYED_ORDER_PENDING";
export const UPDATE_PAYED_ORDER_FULFILLED = "UPDATE_PAYED_ORDER_FULLFILLED";
export const UPDATE_PAYED_ORDER_REJECTED = "UPDATE_PAYED_ORDER_REJECTED";

export const REMOVE_PAYED_ORDER = "REMOVE_PAYED_ORDER";
export const REMOVE_PAYED_ORDER_PAYED = "REMOVE_PAYED_ORDER_PENDING";
export const REMOVE_PAYED_ORDER_FULFILLED = "REMOVE_PAYED_ORDER_FULLFILLED";
export const REMOVE_PAYED_ORDER_REJECTED = "REMOVE_PAYED_ORDER_REJECTED";
