export const ADD_PRODUCT_TO_PENDING_ORDER = "ADD_PRODUCT_TO_ORDER";
export const REMOVE_PRODUCT_FROM_PENDING_ORDER = "REMOVE_PRODUCT_FROM_ORDER";
export const SAVE_PENDING_ORDER_LOCALLY = "SAVE_ORDER_LOCALLY";
export const GET_SAVED_PENDING_ORDER = "GET_PENDING_ORDER_LOCALLY";
export const REMOVE_SAVED_PENDING_ORDER = "REMOVE_SAVED_PENDING_ORDER";
