export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";
export const GET_PRODUCTS_FULFILLED = "GET_PRODUCTS_FULFILLED";
export const GET_PRODUCTS_REJECTED = "GET_PRODUCTS_REJECTED";

export const POST_PRODUCT = "POST_PRODUCT";
export const POST_PRODUCT_PENDING = "POST_PRODUCT_PENDING";
export const POST_PRODUCT_FULFILLED = "POST_PRODUCT_FULFILLED";
export const POST_PRODUCT_REJECTED = "POST_PRODUCT_REJECTED";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_PENDING = "UPDATE_PRODUCT_PENDING";
export const UPDATE_PRODUCT_FULFILLED = "UPDATE_PRODUCT_FULFILLED";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_PENDING = "REMOVE_PRODUCT_PENDING";
export const REMOVE_PRODUCT_FULFILLED = "REMOVE_PRODUCT_FULFILLED";
export const REMOVE_PRODUCT_REJECTED = "REMOVE_PRODUCT_REJECTED";
